# Generated by Django 4.2.5 on 2025-02-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_task_delete_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Task'},
        ),
    ]
